---
abstract: "Perl extension for providing metadata about a module's methods, properties, and arguments"
author:
  - 'James Tillman <jtillman@bigfoot.com>'
build_requires:
  Cwd: 0
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.3
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.133380'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-ModInfo
no_index:
  directory:
    - t
    - inc
  package:
    - MyModule
requires:
  Data::Dumper: 0
  Exporter: 0
  File::Spec::Functions: 0
  IO::File: 0
  Parse::RecDescent: 0
  Template: 0
  XML::DOM: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/neilbowers/Devel-ModInfo.git
version: 2.02
